<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    public function run(): void
    {
        // Bersihkan tabel dulu agar tidak ada data ganda atau bentrok slug
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('companies')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $companies = [
            [
                'id' => 1,
                'slug' => 'kreasi-digital-nusantara',
                'name' => 'Kreasi Digital Nusantara',
                'category' => 'Technology',
                'is_verified' => 1,
                'industry' => 'Software & Web Development',
                'location' => 'Jakarta Selatan',
                'logo' => null,
                'description' => 'Kreasi Digital Nusantara adalah perusahaan teknologi informasi terdepan yang berfokus pada pengembangan solusi digital inovatif, pembuatan aplikasi mobile berskala enterprise, serta layanan konsultasi arsitektur cloud untuk berbagai sektor industri di Indonesia. Kami berkomitmen untuk mendorong transformasi digital yang berkelanjutan bagi UMKM hingga perusahaan multinasional dengan mengedepankan efisiensi, keamanan data, dan pengalaman pengguna yang optimal.',
                'address' => 'Jl. Jendral Sudirman Kav. 52-53, SCBD',
                'city' => 'Jakarta Selatan',
                'work_type' => 'Hybrid',
                'founded_year' => 2018,
                'email' => 'hr@kreasidigital.co.id',
                'whatsapp' => '6281234567890',
                'instagram' => 'kreasidigital_id',
                'facebook' => 'KreasiDigitalNusantara',
                'linkedin' => 'company/kreasi-digital-nusantara',
                'followers_count' => 1250,
                'rating' => 4.90,
                'review_count' => 84,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
            [
                'id' => 2,
                'slug' => 'solusi-pintar-edukasi',
                'name' => 'Solusi Pintar Edukasi',
                'category' => 'Education',
                'is_verified' => 1,
                'industry' => 'EdTech & E-Learning',
                'location' => 'Bandung',
                'logo' => null,
                'description' => 'Solusi Pintar Edukasi (Edutech Group) hadir sebagai pilar utama dalam revolusi pendidikan berbasis digital di Indonesia. Kami mengembangkan platform pembelajaran interaktif terintegrasi yang menghubungkan jutaan pelajar dengan pengajar profesional, menyajikan kurikulum berbasis industri masa depan, serta memfasilitasi pelatihan keterampilan teknis secara mandiri maupun kolaboratif untuk mencetak generasi bangsa yang kompeten dan siap kerja.',
                'address' => 'Jl. Ir. H. Juanda No. 250, Dago',
                'city' => 'Bandung',
                'work_type' => 'Remote',
                'founded_year' => 2019,
                'email' => 'support@solusipintar.edu',
                'whatsapp' => '6289876543210',
                'instagram' => 'solusipintaredukasi',
                'facebook' => 'SolusiPintarEdukasiOfficial',
                'linkedin' => 'company/solusi-pintar-edukasi',
                'followers_count' => 890,
                'rating' => 4.75,
                'review_count' => 56,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
            [
                'id' => 3,
                'slug' => 'matchora-brand',
                'name' => 'Matchora Brand',
                'category' => 'Lainnya',
                'is_verified' => 0,
                'industry' => 'Retail & Consumer Goods',
                'location' => 'Jakarta Pusat',
                'logo' => null,
                'description' => 'Matchora Brand merupakan perusahaan ritel modern dan pengembang produk gaya hidup yang berfokus pada inovasi desain estetis serta kualitas material ramah lingkungan. Didirikan dengan semangat kreativitas tinggi, kami mendistribusikan berbagai produk unggulan yang dirancang khusus untuk memenuhi kebutuhan gaya hidup urban masa kini melalui jaringan pemasaran omnichannel yang luas di seluruh Indonesia.',
                'address' => 'Jl. Merdeka No. 1, Gambir',
                'city' => 'Jakarta',
                'work_type' => 'WFO',
                'founded_year' => 2020,
                'email' => 'info@matchora-brand.com',
                'whatsapp' => '6281122334455',
                'instagram' => 'matchorabrand',
                'facebook' => 'MatchoraBrandID',
                'linkedin' => 'company/matchora-brand',
                'followers_count' => 340,
                'rating' => 4.40,
                'review_count' => 18,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
            [
                'id' => 4,
                'slug' => 'antares-organizer',
                'name' => 'Antares Organize',
                'category' => 'Event & Organizer',
                'is_verified' => 1,
                'industry' => 'Event Management & Production',
                'location' => 'Jakarta Pusat',
                'logo' => null,
                'description' => 'Antares Organize adalah agensi penyedia jasa event organizer profesional dan berpengalaman dalam menangani berbagai skala acara, mulai dari corporate gathering eksklusif, pameran internasional, peluncuran produk prestisius, hingga festival musik akbar. Didukung oleh tim kreatif yang handal, manajemen logistik presisi, serta jejaring vendor luas, kami siap mewujudkan konsep impian Anda menjadi pengalaman yang berkesan.',
                'address' => 'Jl. Sudirman No. 12',
                'city' => 'Jakarta Pusat',
                'work_type' => 'Hybrid',
                'founded_year' => 2019,
                'email' => 'contact@antares-organize.com',
                'whatsapp' => '6285566778899',
                'instagram' => 'antaresorganize',
                'facebook' => 'AntaresOrganizeOfficial',
                'linkedin' => 'company/antares-organize',
                'followers_count' => 620,
                'rating' => 4.60,
                'review_count' => 30,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
            [
                'id' => 5,
                'slug' => 'nusantara-media',
                'name' => 'Nusantara Media',
                'category' => 'Media & Publisher',
                'is_verified' => 1,
                'industry' => 'Digital Media & Journalism',
                'location' => 'Bandung',
                'logo' => null,
                'description' => 'Nusantara Media adalah portal berita, media informasi digital, dan rumah produksi konten kreatif terkemuka yang menyajikan jurnalisme berkualitas tinggi, edukatif, serta inspiratif bagi masyarakat luas. Kami menjembatani arus informasi publik secara transparan dengan memanfaatkan multi-platform digital modern demi mencerdaskan kehidupan bangsa melalui sajian berita yang aktual dan terpercaya.',
                'address' => 'Jl. Asia Afrika No. 45',
                'city' => 'Bandung',
                'work_type' => 'Remote',
                'founded_year' => 2018,
                'email' => 'info@nusantara-media.com',
                'whatsapp' => '6283344556677',
                'instagram' => 'nusantaramedia',
                'facebook' => 'NusantaraMediaNews',
                'linkedin' => 'company/nusantara-media',
                'followers_count' => 1450,
                'rating' => 4.85,
                'review_count' => 92,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
            [
                'id' => 6,
                'slug' => 'matchora-studio',
                'name' => 'Matchora Studio',
                'category' => 'Creative Agency',
                'is_verified' => 1,
                'industry' => 'Design & Branding',
                'location' => 'Yogyakarta',
                'logo' => null,
                'description' => 'Matchora Studio merupakan agensi kreatif independen yang berfokus pada perancangan identitas merek (brand identity), desain UI/UX aplikasi, strategi pemasaran visual, dan produksi multimedia artistik. Kami membantu berbagai bisnis lokal maupun internasional untuk membangun citra visual yang kuat, unik, dan berdaya saing tinggi di pasar global melalui pendekatan artistik yang mendalam.',
                'address' => 'Jl. Kaliurang KM. 5',
                'city' => 'Yogyakarta',
                'work_type' => 'WFO',
                'founded_year' => 2021,
                'email' => 'hello@matchora-studio.com',
                'whatsapp' => '6287788990011',
                'instagram' => 'matchorastudio',
                'facebook' => 'MatchoraStudioCreative',
                'linkedin' => 'company/matchora-studio',
                'followers_count' => 780,
                'rating' => 4.90,
                'review_count' => 45,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
            [
                'id' => 7,
                'slug' => 'sinergi-teknologi',
                'name' => 'Sinergi Teknologi',
                'category' => 'Technology',
                'is_verified' => 1,
                'industry' => 'IT & Software House',
                'location' => 'Jakarta Selatan',
                'logo' => null,
                'description' => 'Sinergi Teknologi adalah perusahaan pengembang perangkat lunak tingkat lanjut (software house) yang menyediakan solusi sistem informasi korporat, integrasi API kompleks, dan infrastruktur keamanan siber yang handal. Visi kami adalah menjadi mitra strategis utama bagi perusahaan yang ingin mempercepat pertumbuhan bisnis melalui adopsi teknologi mutakhir yang aman dan scalable.',
                'address' => 'Jl. HR Rasuna Said, Kuningan',
                'city' => 'Jakarta Selatan',
                'work_type' => 'Hybrid',
                'founded_year' => 2017,
                'email' => 'hr@sinergi-teknologi.com',
                'whatsapp' => '6288899001122',
                'instagram' => 'sinergiteknologi',
                'facebook' => 'SinergiTeknologiID',
                'linkedin' => 'company/sinergi-teknologi',
                'followers_count' => 2100,
                'rating' => 4.95,
                'review_count' => 110,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
            [
                'id' => 8,
                'slug' => 'logistik-kawan',
                'name' => 'Logistik Kawan',
                'category' => 'Logistics',
                'is_verified' => 1,
                'industry' => 'Supply Chain & Logistics',
                'location' => 'Surabaya',
                'logo' => null,
                'description' => 'Logistik Kawan menyediakan layanan ekspedisi kargo cepat, pergudangan modern, dan manajemen rantai pasok (supply chain) terpercaya di seluruh kepulauan Indonesia. Dengan armada pengiriman terintegrasi dan sistem pelacakan real-time, kami menjamin keamanan serta ketepatan waktu pengiriman barang untuk mendukung kelancaran ekosistem perdagangan nasional maupun internasional.',
                'address' => 'Jl. Demak No. 88',
                'city' => 'Surabaya',
                'work_type' => 'WFO',
                'founded_year' => 2016,
                'email' => 'support@logistik-kawan.com',
                'whatsapp' => '6282233445566',
                'instagram' => 'logistikkawan',
                'facebook' => 'LogistikKawanOfficial',
                'linkedin' => 'company/logistik-kawan',
                'followers_count' => 950,
                'rating' => 4.55,
                'review_count' => 48,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
            [
                'id' => 9,
                'slug' => 'edukasi-digital',
                'name' => 'Edukasi Digital',
                'category' => 'Education',
                'is_verified' => 1,
                'industry' => 'EdTech & Online Learning',
                'location' => 'Malang',
                'logo' => null,
                'description' => 'Edukasi Digital merupakan pelopor platform kursus keterampilan teknologi masa depan secara daring (online learning platform) yang dirancang khusus untuk mencetak talenta digital siap kerja. Melalui modul pembelajaran interaktif, bimbingan langsung dari praktisi industri berpengalaman, serta proyek portofolio nyata, kami berdedikasi untuk memajukan kualitas sumber daya manusia di Indonesia.',
                'address' => 'Jl. Ijen No. 10',
                'city' => 'Malang',
                'work_type' => 'Remote',
                'founded_year' => 2020,
                'email' => 'admin@edukasi-digital.com',
                'whatsapp' => '6284455667788',
                'instagram' => 'edukasidigital_id',
                'facebook' => 'EdukasiDigitalOfficial',
                'linkedin' => 'company/edukasi-digital',
                'followers_count' => 1120,
                'rating' => 4.70,
                'review_count' => 64,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
            [
                'id' => 10,
                'slug' => 'sejahtera-abadi',
                'name' => 'PT Sejahtera Abadi',
                'category' => 'Technology',
                'is_verified' => 1,
                'industry' => 'IT Consulting & System Integration',
                'location' => 'Jakarta Barat',
                'logo' => null,
                'description' => 'PT Sejahtera Abadi adalah perusahaan konsultan teknologi informasi yang berfokus pada pengembangan sistem enterprise, integrasi perangkat lunak lintas platform, serta layanan konsultasi infrastruktur IT untuk perusahaan skala menengah hingga besar. Kami berkomitmen membantu klien meningkatkan efisiensi operasional melalui solusi teknologi yang andal, aman, dan mudah diintegrasikan dengan sistem yang sudah berjalan.',
                'address' => 'Jl. Puri Kencana No. 21, Kembangan',
                'city' => 'Jakarta Barat',
                'work_type' => 'Hybrid',
                'founded_year' => 2015,
                'email' => 'hr@sejahtera-abadi.co.id',
                'whatsapp' => '6281299887766',
                'instagram' => 'sejahteraabadi_id',
                'facebook' => 'PTSejahteraAbadi',
                'linkedin' => 'company/sejahtera-abadi',
                'followers_count' => 540,
                'rating' => 4.65,
                'review_count' => 27,
                'created_at' => '2026-09-18 02:40:31',
                'updated_at' => '2026-09-18 02:40:31',
            ],
        ];

        foreach ($companies as $company) {
            DB::table('companies')->insert($company);
        }
    }
}