<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\JobVacancy;
use App\Models\User;
use Illuminate\Support\Str;

class JobVacancySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bayu = User::where('email', 'bayu.2016@alumni.id')->first();
        $dewi = User::where('email', 'dewi.2020@alumni.id')->first();
        $fajar = User::where('email', 'fajar.2015@alumni.id')->first();
        $reza = User::where('email', 'reza.2017@alumni.id')->first();
        $admin = User::where('role', 'admin')->first();

        $jobs = [
            [
                'posted_by' => $bayu?->id ?? $admin?->id,
                'title' => 'Junior UI/UX Designer',
                'slug' => 'junior-ui-ux-designer',
                'company_name' => 'Kreasi Digital Nusantara',
                'company_logo' => 'DS',
                'alumni_contact' => 'Kak Rian (2018)',
                'job_type' => 'Full-Time',
                'workplace_type' => 'Remote',
                'category' => 'Design',
                'highlight_badge' => 'Rekomendasi Alumni',
                'location' => 'Remote / WFH',
                'salary_display' => 'Rp 4.5M - 6.5M / bln',
                'salary_type' => 'per_month',
                'description' => 'Lagi cari pelabuhan karier baru atau mau naik tingkat di dunia desain? Perusahaan yang dibangun sama alumni senior kita lagi buka pintu lebar-lebar buat kamu yang jago bikin tampilan aplikasi jadi ciamik! Yuk, berkarya bareng keluarga sendiri.',
                'requirements' => 'Penguasaan Figma, Design System, Wireframing, dan User Research dasar.',
                'skills_tags' => ['Full-Time', 'Remote', 'Figma'],
                'is_active' => true,
            ],
            [
                'posted_by' => $admin?->id,
                'title' => 'Junior Web Developer',
                'slug' => 'junior-web-developer',
                'company_name' => 'Solusi Pintar Edukasi',
                'company_logo' => 'WD',
                'alumni_contact' => 'Tim Alumni',
                'job_type' => 'Freelance',
                'workplace_type' => 'Hybrid',
                'category' => 'Technology',
                'highlight_badge' => 'Hot Project',
                'location' => 'Jakarta / Hybrid',
                'salary_display' => 'Berdasarkan Project',
                'salary_type' => 'per_project',
                'description' => 'Panggilan buat para pencinta kode dan tukang ngulik database! Perusahaan partner alumni kita lagi butuh bala bantuan nih buat ngembangin sistem informasi sekolah dan manajemen data berbasis web. Anti ribet, asik buat nambah portofolio!',
                'requirements' => 'Memahami dasar PHP, MySQL/XAMPP, JavaScript, dan framework MVC.',
                'skills_tags' => ['Freelance', 'Hybrid', 'PHP & XAMPP'],
                'is_active' => true,
            ],
            [
                'posted_by' => $dewi?->id ?? $admin?->id,
                'title' => 'Content & Social Media Specialist',
                'slug' => 'content-social-media-specialist',
                'company_name' => 'Matchora Brand',
                'company_logo' => 'CM',
                'alumni_contact' => 'Kak Dewi (2020)',
                'job_type' => 'Full-Time',
                'workplace_type' => 'WFO Jakarta',
                'category' => 'Creative & Marketing',
                'highlight_badge' => 'Fresh Grad',
                'location' => 'Jakarta Selatan',
                'salary_display' => 'Rp 4.0M - 5.5M / bln',
                'salary_type' => 'per_month',
                'description' => 'Suka bikin konten seru, ngerti tren TikTok/Reels, dan hobi nulis caption yang jenaka? Jenama kuliner milik alumni kita lagi berkembang pesat dan butuh talenta kreatif yang asyik diajak kerja bareng. Segera daftarkan dirimu!',
                'requirements' => 'Kreatif, memahami algoritma media sosial, dan memiliki kemampuan copywriting yang menarik.',
                'skills_tags' => ['Full-Time', 'WFO Jakarta', 'Copywriting'],
                'is_active' => true,
            ],
            [
                'posted_by' => $admin?->id,
                'title' => 'Community & Event Manager',
                'slug' => 'community-event-manager',
                'company_name' => 'Antares Organizer',
                'company_logo' => 'AO',
                'alumni_contact' => 'Pengurus Pusat',
                'job_type' => 'Full-Time',
                'workplace_type' => 'Bandung / Remote',
                'category' => 'Management',
                'highlight_badge' => 'Special Opening',
                'location' => 'Bandung / Remote',
                'salary_display' => 'Rp 5.0M - 7.0M / bln',
                'salary_type' => 'per_month',
                'description' => 'Punya bakat ngumpulin orang, seru, dan hobi bikin acara kumpul-kumpul yang pecah? Yuk, gabung jadi penggerak utama di balik layar berbagai event seru dan temu kangen alumni kita selanjutnya! Suasana kerja dijamin seru ala keluarga sendiri.',
                'requirements' => 'Pengalaman mengelola event offline/online dan kemampuan komunikasi persuasif.',
                'skills_tags' => ['Full-Time', 'Bandung / Remote', 'Event'],
                'is_active' => true,
            ],
            [
                'posted_by' => $bayu?->id ?? $admin?->id,
                'title' => 'Digital Marketing Growth Specialist',
                'slug' => 'digital-marketing-growth-specialist',
                'company_name' => 'Nusantara Media',
                'company_logo' => 'DM',
                'alumni_contact' => 'Kak Bayu (2016)',
                'job_type' => 'Remote',
                'workplace_type' => 'Remote',
                'category' => 'Marketing',
                'highlight_badge' => 'Fast Growth',
                'location' => 'Remote / WFH',
                'salary_display' => 'Rp 6.0M - 8.5M / bln',
                'salary_type' => 'per_month',
                'description' => 'Mau ngebantu brand lokal milik alumni melesat tinggi lewat strategi iklan digital dan analisis data yang ciamik? Posisi ini pas banget buat kamu yang hobi eksperimen campaign dan baca tren market terkini!',
                'requirements' => 'Pengalaman menjalankan Meta Ads, Google Ads, TikTok Ads, dan Google Analytics.',
                'skills_tags' => ['Full-Time', 'Remote', 'Ads & Analytics'],
                'is_active' => true,
            ],
            [
                'posted_by' => $dewi?->id ?? $admin?->id,
                'title' => 'Graphic Design Intern',
                'slug' => 'graphic-design-intern',
                'company_name' => 'Matchora Studio',
                'company_logo' => 'GI',
                'alumni_contact' => 'Kak Dewi (2020)',
                'job_type' => 'Magang',
                'workplace_type' => 'Hybrid',
                'category' => 'Design',
                'highlight_badge' => 'Intern Program',
                'location' => 'Bandung',
                'salary_display' => 'Rp 2.0M - 3.0M / bln',
                'salary_type' => 'incentive',
                'description' => 'Buat adik-adik tingkat atau fresh graduate yang mau nyari pengalaman nyata di industri kreatif, yuk magang bareng kita! Bakalan dibimbing langsung cara bikin visual brand produk makanan dan minuman yang gemesin.',
                'requirements' => 'Mahir Adobe Illustrator / Photoshop, memiliki portofolio desain visual.',
                'skills_tags' => ['Magang', 'Hybrid', 'Illustrator'],
                'is_active' => true,
            ],
            [
                'posted_by' => $fajar?->id ?? $admin?->id,
                'title' => 'Senior Fullstack Engineer',
                'slug' => 'senior-fullstack-engineer',
                'company_name' => 'Sinergi Teknologi',
                'company_logo' => 'SF',
                'alumni_contact' => 'Kak Fajar (2015)',
                'job_type' => 'Full-Time',
                'workplace_type' => 'Remote',
                'category' => 'Technology',
                'highlight_badge' => 'Tech Lead',
                'location' => 'Remote / WFH',
                'salary_display' => 'Rp 10M - 14M / bln',
                'salary_type' => 'per_month',
                'description' => 'Punya pengalaman matang di framework Laravel dan terbiasa merancang arsitektur sistem skala besar? Senior kita lagi bangun tim impian dan butuh tangan kanan handal buat nakhodain project-project skala nasional!',
                'requirements' => 'Minimal 3 tahun pengalaman Laravel, Vue.js/React, REST API, Database Optimization.',
                'skills_tags' => ['Full-Time', 'Remote', 'Laravel & Vue'],
                'is_active' => true,
            ],
            [
                'posted_by' => $admin?->id,
                'title' => 'Podcast Host & Copywriter',
                'slug' => 'podcast-host-copywriter',
                'company_name' => 'Ngobrol Bareng Alumni',
                'company_logo' => 'PH',
                'alumni_contact' => 'Tim Media',
                'job_type' => 'Freelance',
                'workplace_type' => 'Studio Jakarta',
                'category' => 'Media & Broadcasting',
                'highlight_badge' => 'Kreatif & Seru',
                'location' => 'Jakarta Selatan',
                'salary_display' => 'Per Episode',
                'salary_type' => 'per_episode',
                'description' => 'Pede ngomong di depan kamera/mikrofon, punya suara renyah, dan hobi ngulik cerita unik dari para alumni sukses? Gabung jadi host program bincang-bincang santai kita yuk! Pastinya seru dan nambah relasi luas.',
                'requirements' => 'Public speaking yang luwes, percaya diri, dan kemampuan improvisasi wawancara.',
                'skills_tags' => ['Freelance', 'Studio Jakarta', 'Public Speaking'],
                'is_active' => true,
            ],
            [
                'posted_by' => $reza?->id ?? $admin?->id,
                'title' => 'Operations & Supply Chain Lead',
                'slug' => 'operations-supply-chain-lead',
                'company_name' => 'Logistik Kawan',
                'company_logo' => 'LK',
                'alumni_contact' => 'Kak Reza (2017)',
                'job_type' => 'Full-Time',
                'workplace_type' => 'On-Site Surabaya',
                'category' => 'Operations',
                'highlight_badge' => 'Hot Demand',
                'location' => 'Surabaya',
                'salary_display' => 'Rp 7.5M - 10M / bln',
                'salary_type' => 'per_month',
                'description' => 'Jago ngatur logistik, manajemen gudang, dan koordinasi mitra bisnis dengan efisien? Perusahaan ekspedisi milik alumni kita lagi butuh sosok pemimpin operasional yang cekatan dan solutif.',
                'requirements' => 'Pengalaman operasional warehouse, fleet management, dan vendor negotiation.',
                'skills_tags' => ['Full-Time', 'On-Site Surabaya', 'Supply Chain'],
                'is_active' => true,
            ],
            [
                'posted_by' => $admin?->id,
                'title' => 'Customer Happiness Officer',
                'slug' => 'customer-happiness-officer',
                'company_name' => 'Edukasi Digital',
                'company_logo' => 'CH',
                'alumni_contact' => 'Tim Alumni',
                'job_type' => 'Remote',
                'workplace_type' => 'Remote',
                'category' => 'Customer Support',
                'highlight_badge' => 'Junior Friendly',
                'location' => 'Remote / WFH',
                'salary_display' => 'Rp 4.0M - 5.5M / bln',
                'salary_type' => 'per_month',
                'description' => 'Punya empati tinggi, sabar, ramah, dan suka bantu orang lain mecahin masalah seputar aplikasi belajar online? Posisi ini sangat ramah buat fresh graduate yang mau merintis karier di dunia startup edukasi.',
                'requirements' => 'Kemampuan komunikasi tulisan & lisan yang baik, ramah, dan solutif.',
                'skills_tags' => ['Full-Time', 'Remote', 'Communication'],
                'is_active' => true,
            ],
        ];

        foreach ($jobs as $job) {
            JobVacancy::updateOrCreate(['slug' => $job['slug']], $job);
        }
    }
}
